### ISSUE TITLE
Magic condition

### ISSUE THREAD

**Issue by IanaKhitsko** [kirick1/project-technologies#6]
https://github.com/kirick1/project-technologies/blob/bffa0854a4384dc9ba3ce69e652093d298e25a06/index.ts#L13

Please explain this magic condition. why lineIndex < lines.length - 2 ?

**Comment by kirick1** [comment]
Because loop starts reading input file and try to find digit in first line that represents count of countries in test case, after that if completes checking next lines with info about countries and since the last row consists of one zero, so we can skip it, and it makes no sense to check the line before it because it does not exactly describe the test case
